# Generated by Django 3.1.2 on 2021-11-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
